openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /translate/{text}:
    get:
      summary: Read Item
      operationId: read_item_translate__text__get
      parameters:
        - required: true
          schema:
            title: Text
            type: string
          name: text
          in: path
        - description: Language of the text
          required: false
          schema:
            title: Source language
            type: string
            description: Language of the text
          name: src_lang
          in: query
        - description: Language of the translation
          required: false
          schema:
            title: Target language
            type: string
            description: Language of the translation
          name: trg_lang
          in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /synthesize/{text}:
    get:
      summary: Read Item
      operationId: read_item_synthesize__text__get
      parameters:
        - required: true
          schema:
            title: Text
            type: string
          name: text
          in: path
        - description: Language of the text
          required: false
          schema:
            title: Source language
            type: string
            description: Language of the text
          name: src_lang
          in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
